project/cuisines/routes.py
from flask import Flask, render_template, request, flash, redirect, url_for, Blueprint, make_response, session
from flask_pymongo import pymongo
from project import mongo
from bson.objectid import ObjectId
import math
from functools import wraps
from project import auth_required

all_cuisines = Blueprint('all_cuisines', __name__)

#List of all cuisines
@all_cuisines.route('/get_cuisines')
@auth_required
def get_cuisines():
    return render_template('cuisines.html', cuisines=mongo.db.cuisines.find().sort('cuisine_name', pymongo.ASCENDING))

#List of recipes for particular cuisine
@all_cuisines.route('/recipes_for/<cuisine_id>')
@auth_required
def recipes_for(cuisine_id):
    cuisine = mongo.db.cuisines.find_one({"_id":ObjectId(cuisine_id)})
    cuisines =  mongo.db.cuisines.find()
    recipes = mongo.db.recipes.find().sort('recipe_name', pymongo.ASCENDING)
    return render_template('recipesfor.html', recipes=recipes, cuisine=cuisine)
    
#Edit selected cuisine    
@all_cuisines.route('/edit_cuisine/<cuisine_id>')
@auth_required
def edit_cuisine(cuisine_id):
    return render_template('editcuisine.html',
    cuisine=mongo.db.cuisines.find_one({'_id': ObjectId(cuisine_id)}))

#Update selected cuisine
@all_cuisines.route('/update_cuisine/<cuisine_id>', methods=['POST'])
@auth_required
def update_cuisine(cuisine_id):
    mongo.db.cuisines.update(
        {'_id': ObjectId(cuisine_id)},
        {'cuisine_name': request.form.get('cuisine_name')})
    flash("You've updated the cuisine successfully")
    return redirect(url_for('all_cuisines.get_cuisines'))

#Delete selected cuisine
@all_cuisines.route('/delete_cuisine/<cuisine_id>')
@auth_required
def delete_cuisine(cuisine_id):
    mongo.db.cuisines.remove({'_id': ObjectId(cuisine_id)})
    flash("You've deleted the cuisine successfully")
    return redirect(url_for('all_cuisines.get_cuisines'))

#Add a new cuisine    
@all_cuisines.route('/new_cuisine')
@auth_required
def new_cuisine():
    return render_template('addcuisine.html')

#Insert a new cuisine to the data base
@all_cuisines.route('/insert_cuisine', methods=["POST"])
@auth_required
def insert_cuisine():
    cuisines = mongo.db.cuisines
    cuisine_data = {'cuisine_name': request.form.get('cuisine_name')}
    cuisines.insert_one(cuisine_data)
    flash("You've added a new cuisine")
    return redirect(url_for('all_cuisines.get_cuisines'))

project/login/routes.py
# The idea for the login functionality was taken from: https://www.youtube.com/watch?v=vVx1737auSE
from project import mongo
from flask import Flask, render_template, request, session, flash, redirect, url_for, Blueprint 
from flask_pymongo import pymongo
import bcrypt

login_function = Blueprint('login_function', __name__)

#Login page
@login_function.route("/login")
def login():
    return render_template('login.html')

#Send login data to the database   
@login_function.route('/login_form', methods=['POST'])
def login_form():
    users = mongo.db.users
    login_user = users.find_one({'name' : request.form['username']})
    
    if login_user:
        if bcrypt.hashpw(request.form['password'].encode('utf-8'), login_user['password']) == login_user['password']:
            session['username'] = request.form['username']
            flash("You are logged in")
        return redirect(url_for('homepage.index'))
    return 'Invalid username or password'
    
#Add a new user to the database    
@login_function.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        users = mongo.db.users
        existing_user = users.find_one({'name' : request.form['username']})
        
        if existing_user is None:
            hashpass = bcrypt.hashpw(request.form['password'].encode('utf-8'), bcrypt.gensalt())
            users.insert({'name' : request.form['username'], 'password' : hashpass})
            session['username'] = request.form['username']
            flash("Your account has benn created")
            return redirect(url_for('homepage.index'))
        return 'That username already exists!'
    return render_template("register.html")

#Logout
@login_function.route('/logout')
def logout():
    session.clear()
    flash("You have been logged out successfully")
    return redirect(url_for('homepage.welcome'))

project/recipes/routes.py
import math
from flask import Flask, render_template, request, flash, redirect, url_for, Blueprint, make_response, session
from flask_pymongo import pymongo
from project import mongo
from bson.objectid import ObjectId
from functools import wraps
from project import auth_required

all_recipes = Blueprint('all_recipes', __name__)

#Show all the recipes
@all_recipes.route('/get_recipes')
@auth_required
def get_recipes():
    page_limit = 3
    current_page = int(request.args.get('current_page', 1))
    total = mongo.db.recipes.count()
    pages = range(1, int(math.ceil(total / page_limit)) + 1)
    recipes = mongo.db.recipes.find().sort('_id', pymongo.ASCENDING).skip((current_page - 1)*page_limit).limit(page_limit)
    
    return render_template('recipes.html', recipes=recipes, current_page=current_page, pages=pages)

#Search for the particular recipe
@all_recipes.route('/search')
@auth_required
def search():
    page_limit = 3 #Logic for pagination
    current_page = int(request.args.get('current_page', 1))
    db_query = request.args['db_query']
    total = mongo.db.recipes.find({'$text': {'$search': db_query }})
    pages = range(1, int(math.ceil(total.count() / page_limit)) + 1)
    
    results = mongo.db.recipes.find({'$text': {'$search': db_query }}).sort('_id', pymongo.ASCENDING).skip((current_page - 1)*page_limit).limit(page_limit)
    return render_template('search.html', results=results, pages=pages, current_page=current_page, db_query=db_query)

#Add a new recipe
@all_recipes.route('/add_recipe')
@auth_required
def add_recipe():
    return render_template('addrecipe.html', cuisines=mongo.db.cuisines.find().sort('cuisine_name', pymongo.ASCENDING))
    
#Insert a new recipe to the database
@all_recipes.route('/insert_recipe',methods=["POST"])
@auth_required
def insert_recipe():
    recipes = mongo.db.recipes
    new_recipe = ({
        'recipe_name': request.form.get('recipe_name'),
        'cuisine_name': request.form.get('cuisine_name'),
        'preparation_time': request.form.get('preparation_time'),
        'cooking_time': request.form.get('cooking_time'),
        'serves': request.form.get('serves'),
        'ingredients': request.form.getlist('ingredient'),
        'method': request.form.getlist('step'),
        'date_posted': request.form.get('date_posted'),
        'image': request.form.get('image')
    })
    recipes.insert_one(new_recipe)
    flash("You've added a new recipe")
    return redirect(url_for('all_recipes.get_recipes'))

#Edit selected recipe
@all_recipes.route('/edit_recipe/<recipe_id>')
@auth_required
def edit_recipe(recipe_id):
    the_recipe = mongo.db.recipes.find_one({"_id":ObjectId(recipe_id)})
    all_cuisines = mongo.db.cuisines.find().sort('cuisine_name', pymongo.ASCENDING)
    return render_template('editrecipe.html', recipe=the_recipe, cuisines=all_cuisines)

#Update selected recipe
@all_recipes.route('/update_recipe/<recipe_id>', methods=['POST'])
@auth_required
def update_recipe(recipe_id):
    recipes = mongo.db.recipes
    recipes.update( {'_id': ObjectId(recipe_id)},
    {
        'recipe_name': request.form.get('recipe_name'),
        'cuisine_name': request.form.get('cuisine_name'),
        'preparation_time': request.form.get('preparation_time'),
        'cooking_time': request.form.get('cooking_time'),
        'serves': request.form.get('serves'),
        'ingredients': request.form.getlist('ingredient'),
        'method': request.form.getlist('step'),
        'date_posted': request.form.get('date_posted'),
        'image': request.form.get('image')
    })
    flash("You've updated the recipe successfully")
    return redirect(url_for('all_recipes.get_recipes'))
    
#Delete selected recipe from the database  
@all_recipes.route('/delete_recipe/<recipe_id>')
@auth_required
def delete_recipe(recipe_id):
    mongo.db.recipes.remove({'_id': ObjectId(recipe_id)})
    flash("You've deleted the recipe successfully")
    return redirect(url_for('all_recipes.get_recipes'))
    

project/statistics/routes.py
import os
from flask import Flask, render_template, request, flash, redirect, url_for, Blueprint, session, make_response
from pymongo import MongoClient
from bson.json_util import dumps
import json
from bson import json_util
from functools import wraps
from project import auth_required

#Configuration for the concetion between charts and the database
DBS_NAME = 'cooking_book'
COLLECTION_NAME = 'recipes'
FIELDS = {'recipe_name': True, 'cuisine_name': True, 'preparation_time': True, 'cooking_time': True, 'date_posted':True, '_id': False}
statistics_function = Blueprint('statistics_function', __name__)


#Subpage with the charts
@statistics_function.route("/statistics")
@auth_required
def statistics():
    return render_template("statistics.html")

#Download data from the database to the charts
@statistics_function.route("/statistics/recipes")
@auth_required
def recipes():
    connection = MongoClient(os.environ.get("MONGO_URI"))
    collection = connection[DBS_NAME][COLLECTION_NAME]
    recipes = collection.find(projection=FIELDS)
    json_recipes = []
    for recipe in recipes:
        json_recipes.append(recipe)
    json_recipes = json.dumps(json_recipes, default=json_util.default)
    connection.close()
    return json_recipes

project/templates/addcuisine.html
{% extends 'base.html' %} 
{% block content %}
</nav>
<!--Add cuisine form-->
    <div class="container blocks">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="ml-5">Add cuisine</h2>
                <form action="{{ url_for('all_cuisines.insert_cuisine') }}" method="POST">
                    <div class="form-row align-items-center mt-5">

                        <div class="col-lg-10 ml-5">
                            <label class="sr-only" for="cuisine_name ">Cuisine name</label>
                            <p>Cusine name</p>
                            <div class="input-group mb-2">
                                <input type="text" class="form-control" id="cuisine_name" name="cuisine_name" required>
                            </div>
                        </div>

                        <div class="col-lg-10 ml-5">
                            <button type="submit" class="btn btn-outline-primary btn-radius mt-2 mb-2">Add Cuisine</button> 
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<div>
<!--Breadcrumbs-->
<nav class="breadcrumb1" aria-label="breadcrumb  ">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item"><a href="{{ url_for('homepage.index') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('all_cuisines.get_cuisines') }}">Manage Cuisines</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add Cuisine</li>
  </ol>
</nav>
</div>
{% endblock %}

project/templates/cuisines.html
{% extends 'base.html' %} {% block content %}
</nav>
<!--List of cuisines-->
<div class="container blocks ">
    {% for cuisine in cuisines %}
    <div class="row border border-secondary rounded">
        <div class="col-lg-8 ingredients">
            <h1 class="display-5">{{ loop.index }}. <a href="{{url_for('all_cuisines.recipes_for', cuisine_id=cuisine._id)}}">{{cuisine.cuisine_name}}</a></h1>
        </div>
        <div class="mt-4">
            <a href="{{url_for('all_cuisines.edit_cuisine', cuisine_id=cuisine._id)}}" class="btn btn-outline-primary btn-lg btn-radius" role="button" aria-pressed="true">Edit</a>
            <a href="{{url_for('all_cuisines.delete_cuisine', cuisine_id=cuisine._id)}}" class="btn btn-outline-danger btn-lg btn-radius ml-2" role="button" aria-pressed="true">Delete</a>
        </div>
    </div>
    <hr class="divider my-4"> {% endfor %}
    <div class="mb-4">
        <a href="{{url_for('all_cuisines.new_cuisine')}}" class="btn btn-outline-success btn-lg btn-radius" role="button" aria-pressed="true">Add Cuisine</a>
    </div>
</div>

<!--Breadcrumbs-->
<div>
    <nav aria-label="breadcrumb my-0 ">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{ url_for('homepage.index') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Manage Cuisines</li>
        </ol>
    </nav>
</div>
{% endblock %}

project/templates/footer.html
    <footer class="py-4  bg-secondary">
        <div>
        <p class=" text-center text-white">Cooking Recipes by Marcin Marciszewski</p>
        {% if 'username' in session %}
        <p class=" text-center bg-dark text-white">Logged in as : {{ session['username'].title() }}</p>
        {% endif %}
       </div>
    </footer>

project/templates/login.html
{% extends "base.html" %}
{% block content %}
</nav>
<div class="container-fluid bg_login">
    <div class="row">
        <div class="col-lg-4 offset-lg-4 user_form ">
            <form class="form-container" method=POST action="{{ url_for('login_function.login_form') }}" >
                <h1>Please login</h1>
                <div class="form-group  mt-5">
                    <input type="text" class="form-control" name="username" placeholder="Username" required>
                </div>
                <div class="form-group  mt-5">
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                </div>
                <div class="text-center">
                <button type="submit" class="btn btn-outline-light btn-radius mt-5">Log In</button>
                </div>
            </form>
            <br>
            <div id="reg-link">
                Don't have an account? <a href="{{ url_for('login_function.register') }}">Sign up here</a>.
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/templates/recipes.html
{% extends 'base.html' %} {% block content %}
</nav>
<!--Card with a recipe-->
<div class="container blocks ">
    {% for recipe in recipes %}
    <div class="border border-secondary rounded">
        <div class="row">
            <div class="col-lg-8 ">
                <h1 class="display-4">{{ recipe.recipe_name }}</h1>
                <h2 class="display-5">{{ recipe.cuisine_name }}</h2>
            </div>
            <div class="col-lg-4">
                <img class="rounded" src="{{ recipe.image }}" alt="recipe image">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 ingredients">
                <h2>Ingredients: </h2>
                {% for ingredient in recipe.ingredients %}
                <p class="lead">{{ loop.index }}. {{ ingredient }}</p>
                {% endfor %}
                <h2 class="mt-4">Method: </h2>
                {% for step in recipe.method %}
                <p class="lead">{{ loop.index }}. {{ step }}</p>
                {% endfor %}
            </div>
            <div class="col-lg-4 preparation">
                <p><span>Preparation time: </span>{{ recipe.preparation_time }}</p>
                <p><span>Cooking time: </span>{{ recipe.cooking_time }}</p>
                <p><span>Serves: </span>{{ recipe.serves }}</p>
                <p><span>Date: </span>{{ recipe.date_posted }}</p>
            </div>
            <a href="{{ url_for('all_recipes.edit_recipe', recipe_id=recipe._id) }}" class="btn btn-outline-primary btn-lg btn-radius ml-3" role="button" aria-pressed="true">Edit</a>
            <a href="{{ url_for('all_recipes.delete_recipe', recipe_id=recipe._id) }}" class="btn btn-outline-danger btn-lg btn-radius ml-2" role="button" aria-pressed="true">Delete</a>
        </div>
    </div>
    <hr class="divider my-5"> {% endfor %}
    <!--If there is no recipes yet-->
    <div id="hide">
        <p>No recipes yet!</p>
    </div>
    <!--Pagination-->
    <div class="pagin">
        <ul class="pagination flex-wrap">
            {% for page_number in pages %} {% if page_number == current_page %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('all_recipes.get_recipes', current_page=page_number) }}">{{ page_number }}</a></li>
            {% endif %} {% endfor %}
        </ul>
    </div>
    <a href="{{ url_for('all_recipes.add_recipe') }}" class="btn btn-outline-success btn-lg btn-radius mt-3 " role="button" aria-pressed="true">Add recipe</a>
</div>
<!--Breadcrumbs-->
<div>
    <nav aria-label="breadcrumb my-0 ">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{ url_for('homepage.index') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Recipes</li>
        </ol>
    </nav>
</div>
{% endblock %}

project/templates/recipesfor.html
{% extends 'base.html' %} {% block content %}>
</nav>
<div class="container blocks ">
    {% for recipe in recipes %}     
    {% if recipe.cuisine_name == cuisine.cuisine_name %}
       <div class="border border-secondary rounded">
        <div class="row">
            <div class="col-lg-8 ">
                <h1 class="display-4">{{ recipe.recipe_name }}</h1>
                <h2 class="display-5">{{ recipe.cuisine_name }}</h2>
            </div>
            <div class="col-lg-4">
                <img class="rounded" src="{{ recipe.image }}" alt="recipe image">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 ingredients">
                <h2>Ingredients: </h2>
                {% for ingredient in recipe.ingredients %}
                <p class="lead">{{ loop.index }}. {{ ingredient }}</p>
                {% endfor %}
                <h2 class="mt-4">Method: </h2>
                {% for step in recipe.method %}
                <p class="lead">{{ loop.index }}. {{ step }}</p>
                {% endfor %}
            </div>
            <div class="col-lg-4 preparation">
                <p><span>Preparation time: </span>{{ recipe.preparation_time }}</p>
                <p><span>Cooking time: </span>{{ recipe.cooking_time }}</p>
                <p><span>Serves: </span>{{ recipe.serves }}</p>
                <p><span>Date: </span>{{ recipe.date_posted }}</p>
            </div>
            <a href="{{ url_for('all_recipes.edit_recipe', recipe_id=recipe._id) }}" class="btn btn-outline-primary btn-lg btn-radius ml-3" role="button" aria-pressed="true">Edit</a>
            <a href="{{ url_for('all_recipes.delete_recipe', recipe_id=recipe._id) }}" class="btn btn-outline-danger btn-lg btn-radius ml-2" role="button" aria-pressed="true">Delete</a>
        </div>
    </div>
    <hr class="divider my-5"> {% endif %} {% endfor %}
    <!--If there is no recipes yet-->
    <div id="hide">
        <p>No recipes yet!</p>
    </div>
    <a href="{{ url_for('all_recipes.add_recipe') }}" class="btn btn-outline-success btn-lg btn-radius mt-3 " role="button" aria-pressed="true">Add recipe</a>
</div>
<!--Breadcrumbs-->
<div>
    <nav aria-label="breadcrumb my-0 ">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{ url_for('homepage.index') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('all_cuisines.get_cuisines') }}">Cuisines</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{cuisine.cuisine_name}}</li>
        </ol>
    </nav>
</div>

{% endblock %}

project/templates/register.html
{% extends "base.html" %}
{% block content %}
</nav>
<div class="container-fluid mt-5 bg_register">
    <div class="row">
        <div class="col-lg-4 offset-lg-4 user_form">
            
            <form class="form-container" method=POST action="{{ url_for('login_function.register') }}">
                <h1>Please register</h1>
                <div class="form-group">
                    <input type="text" class="form-control mt-5" name="username" placeholder="Username" required>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control mt-5" name="password" placeholder="Password" required >
                </div>
                <div class="text-center ">
                <button type="submit" class="btn btn-outline-light btn-radius mt-5">Register</button>
                </div>
            </form>
            <br>
        </div>
    </div>
</div>
{% endblock %}

project/templates/search.html
{% extends 'base.html' %} {% block content %}
</nav>
<div class="container blocks ">
    {% for recipe in results %}
    <div class="border border-secondary rounded">   
    <div class="row">
        <div class="col-lg-8 ">
            <h1 class="display-4">{{ recipe['recipe_name'] }}</h1>
            <h2 class="display-5">{{ recipe['cuisine_name'] }}</h2>
        </div>
        <div class="col-lg-4">
            <img src="{{ recipe['image'] }}" alt="recipe image">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 ingredients">
            <h2>Ingredients: </h2>
            {% for ingredient in recipe.ingredients %}
            <p class="lead">{{ loop.index }}. {{ ingredient }}</p>
            {% endfor %}
            <h2>Method: </h2>
            {% for step in recipe.method %}
            <p class="lead">{{ loop.index }}. {{ step }}</p>
            {% endfor %}
        </div>
        <div class="col-lg-4 preparation">
            <p><span>Preparation time: </span>{{ recipe['preparation_time'] }}</p>
            <p><span>Cooking time: </span>{{ recipe['cooking_time'] }}</p>
            <p><span>Serves: </span>{{ recipe['serves'] }}</p>
            <p><span>Date: </span>{{ recipe['date_posted'] }}</p>
        </div>
        <a href="{{ url_for('all_recipes.edit_recipe', recipe_id=recipe._id) }}" class="btn btn-outline-primary btn-lg btn-radius ml-3" role="button" aria-pressed="true">Edit</a>
        <a href="{{ url_for('all_recipes.delete_recipe', recipe_id=recipe._id) }}" class="btn btn-outline-danger btn-lg btn-radius ml-2" role="button" aria-pressed="true">Delete</a>
    </div>
</div>
    <hr class="divider my-5"> 
    
    {% endfor %}
    <div id="hide">
        <p>No recipes yet!</p>
    </div>

    <div class="pagin">
        <ul class="pagination flex-wrap">
            {% for page_number in pages %} {% if page_number == current_page %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('all_recipes.search', current_page=page_number, db_query=db_query) }}">{{ page_number }}</a></li>
            {% endif %} {% endfor %}
        </ul>
    </div>
    <a href="{{ url_for('all_recipes.add_recipe') }}" class="btn btn-outline-success btn-lg btn-radius mt-3 " role="button" aria-pressed="true">Add recipe</a>
</div>
<!--Breadcrumbs-->
<div>
    <nav aria-label="breadcrumb my-0 ">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{ url_for('homepage.index') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Recipes</li>
        </ol>
    </nav>
</div>
{% endblock %}

project/templates/welcome.html
{% extends 'base.html' %} {% block navbar %}
<!--Navbar-->
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
<div class="collapse navbar-collapse text-light mr-5" id="navbarResponsive">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      {% if 'username' in session %}
      <a class="nav-link js-scroll-trigger" href="{{url_for('login_function.logout') }}">Log Out</a> 
      {% else %}
      <a class="nav-link js-scroll-trigger" href="{{url_for('login_function.login') }}">Log In</a> 
      {% endif %}
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="{{url_for('login_function.register') }}">Sign Up</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="#about">About</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="#cuisines">Cuisines</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
    </li>
  </ul>
</div>
</nav>
<!--Carousel-->
{% endblock %} {% block carousel %}
<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="2500">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active" style="background-image: url('/static/img/carousel/1.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-3">Add a new recipe</h2>
        </div>
      </div>
      <div class="carousel-item" style="background-image: url('/static/img/carousel/2.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-3">Create your own cooking book</h2>
        </div>
      </div>
      <div class="carousel-item" style="background-image: url('/static/img/carousel/3.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-3">Share your recipes with friends</h2>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>
</header>
{% endblock %} {% block about %}
<!--About section-->
<section id="about">
  <div class="container">
    <div class="row">
      <div  class="col-lg-12 mx-auto text-center">
        <h2 >Recipes manager</h2>
        <p class="lead">Whether your passion is cooking or you just love to eat, we are sure that you have a collection of dishes and recipes you'd like to try and share. Maybe you have a bunch handed down from your mother. In either case, you probably need a better
          method to keep them organized. We have created this website to make your life easier so you can spend more time enjoying cooking. Just create your account and start enjoyoing our service.</p>
      </div>
    </div>
   </div>
</section>
{% endblock %} {% block content %}
<!--Cuisines section-->
<section id="cuisines" class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 mx-auto text-center pb-5">
        <h2 >Cuisines</h2>
        <p class="lead">You can browse all cuisines, add more and edit existing. Click on any of them to get a list of added recipes.<br> We also prepared a bunch of statistics for you. </p>
      </div>
    </div>
</section>
{% endblock %} {% block send_message %}
<!-- Contact Section -->
<section id="contact" class="page-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="mt-0">Let's Get In Touch!</h2>
        <hr class="divider my-4 ml-10 text-center">
        <p class="text-dark mb-5"> Give us a call or send us an email and we will get back to you as soon as possible!</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center">
        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
        <div>+1 (202) 555-0149</div>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <a href="{{ url_for ('mail_function.mailto') }}"><i class="fas fa-envelope fa-3x mb-3 text-muted"></i></a>
        <div class="d-block">Send a message to us</div>
      </div>
    </div>
  </div>
</section>
{% endblock %} {% block footer %} {% include 'footer.html' %} {% endblock %}